In [3]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

In [4]:
from dotenv import load_dotenv

load_dotenv()

True

In [5]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [6]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [8]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [10]:
books["tagged_description"].to_csv("tagged_description.txt",
                                    index=False,
                                    header=False)

In [6]:
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=1, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 375, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 483, which is longer than the specified 1
Created a chunk of size 484, which is longer than the specified 1
Created a chunk of size 962, which is longer than the specified 1
Created a chunk of size 188, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1
Created a chunk of size 296, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1

Created a chunk of size 881, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 213, which is longer than the specified 1
Created a chunk of size 216, which is longer than the specified 1
Created a chunk of size 515, which is longer than the specified 1
Created a chunk of size 754, which is longer than the specified 1
Created a chunk of size 390, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 253, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 730, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 258, which is longer than the specified 1
Created a chunk of size 475, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 1267, which is longer than the specified 1
Created a chunk of size 683, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 555, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 282, which is longer than the specified 1
Created a chunk of size 789, which is longer than the specified 1
Created a chunk of size 566, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 299, which is longer than the specified 1
Created a chunk of size 535, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 565, which is longer than the specified 1
Created a chunk of size 385, which is longer than the specified 1
Created a chunk of size 412, which is longer than the specified 1
Created a chunk of size 463, which is longer than the specified 1
Created a chunk of size 597, which is longer than the specified 1
Created a chunk of size 478, which is longer than the specified 1
Created a chunk of size 461, which is longer than the specified 1
Created a chunk of size 259, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 616, which is longer than the specified 1
Created a chunk of size 421, which is longer than the specified 1
Created a chunk of size 889, which is longer than the specified 1
Created a chunk of size 695, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 219, which is longer than the specified 1
Created a chunk of size 277, which is longer than the specified 1
Created a chunk of size 2010, which is longer than the specified 1
Created a chunk of size 175, which is longer than the specified 1
Created a chunk of size 481, which is longer than the specified 1
Created a chunk of size 302, which is longer than the specified 1
Created a chunk of size 522, which is longer than the specified 1
Created a chunk of size 649, which is longer than the specified 1
Created a chunk of size 778, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 550, which is longer than the specified 1
Created a chunk of size 1225, which is longer than the specified 1
Created a chunk of size 408, which is longer than the specified 1
Created a chunk of size 1186, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 1193, which is longer than the specified 1
Created a chunk of size 1059, which is longer than the specified 1
Created a chunk of size 246, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 878, which is longer than the specified 1
Created a chunk of size 286, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 419, which is longer than the specified 1
Created a chunk of size 210, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 528, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 340, which is longer than the specified 1
Created a chunk of size 901, which is longer than the specified 1
Created a chunk of size 1272, which is longer than the specified 1
Created a chunk of size 560, which is longer than the specified 1
Created a chunk of size 1637, which is longer than the specified 1
Created a chunk of size 438, which is longer than the specified 1
Created a chunk of size 251, which is longer than the specified 1
Created a chunk of size 779, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 516, which is longer than the specified 1
Created a chunk of size 960, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1132, which is longer than the specified 1
Created a chunk of size 170, which is longer than the specified 1
Created a chunk of size 1325, which is longer than the specified 1
Created a chunk of size 853, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 801, which is longer than the specified 1
Created a chunk of size 1121, which is longer than the specified 1
Created a chunk of size 838, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 734, which is longer than the specified 1
Created a chunk of size 1195, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 775, which is longer than the specified 1
Created a chunk of size 280, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 358, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 2012, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 1288, which is longer than the specified 1
Created a chunk of size 1231, which is longer than the specified 1
Created a chunk of size 729, which is longer than the specified 1
Created a chunk of size 750, which is longer than the specified 1
Created a chunk of size 447, which is longer than the specified 1
Created a chunk of size 1242, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 914, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 846, which is longer than the specified 1
Created a chunk of size 1128, which is longer than the specified 1
Created a chunk of size 1075, which is longer than the specified 1
Created a chunk of size 1320, which is longer than the specified 1
Created a chunk of size 363, which is longer than the specified 1
Created a chunk of size 2834, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 208, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 1006, which is longer than the specified 1
Created a chunk of size 715, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 2510, which is longer than the specified 1
Created a chunk of size 956, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 351, which is longer than the specified 1
Created a chunk of size 641, which is longer than the specified 1
Created a chunk of size 405, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 795, which is longer than the specified 1
Created a chunk of size 167, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 1424, which is longer than the specified 1
Created a chunk of size 1085, which is longer than the specified 1
Created a chunk of size 1146, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 790, which is longer than the specified 1
Created a chunk of size 297, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 876, which is longer than the specified 1
Created a chunk of size 808, which is longer than the specified 1
Created a chunk of size 1814, which is longer than the specified 1
Created a chunk of size 1830, which is longer than the specified 1
Created a chunk of size 1064, which is longer than the specified 1
Created a chunk of size 955, which is longer than the specified 1
Created a chunk of size 1182, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 288, which is longer than the specified 1
Created a chunk of size 1286, which is longer than the specified 1
Created a chunk of size 1644, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 1932, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 2008, which is longer than the specified 1
Created a chunk of size 2285, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 1003, which is longer than the specified 1
Created a chunk of size 579, which is longer than the specified 1
Created a chunk of size 290, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 1144, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 1483, which is longer than the specified 1
Created a chunk of size 223, which is longer than the specified 1
Created a chunk of size 1137, which is longer than the specified 1
Created a chunk of size 724, which is longer than the specified 1
Created a chunk of size 668, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 608, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 967, which is longer than the specified 1
Created a chunk of size 859, which is longer than the specified 1
Created a chunk of size 1034, which is longer than the specified 1
Created a chunk of size 191, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 497, which is longer than the specified 1
Created a chunk of size 652, which is longer than the specified 1
Created a chunk of size 350, which is longer than the specified 1
Created a chunk of size 735, which is longer than the specified 1
Created a chunk of size 527, which is longer than the specified 1
Created a chunk of size 1017, which is longer than the specified 1
Created a chunk of size 972, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 546, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 378, which is longer than the specified 1
Created a chunk of size 933, which is longer than the specified 1
Created a chunk of size 564, which is longer than the specified 1
Created a chunk of size 856, which is longer than the specified 1
Created a chunk of size 717, which is longer than the specified 1
Created a chunk of size 749, which is longer than the specified 1
Created a chunk of size 714, which is longer than the specified 1
Created a chunk of size 326, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 229, which is longer than the specified 1
Created a chunk of size 706, which is longer than the specified 1
Created a chunk of size 1914, which is longer than the specified 1
Created a chunk of size 397, which is longer than the specified 1
Created a chunk of size 487, which is longer than the specified 1
Created a chunk of size 622, which is longer than the specified 1
Created a chunk of size 561, which is longer than the specified 1
Created a chunk of size 558, which is longer than the specified 1
Created a chunk of size 388, which is longer than the specified 1
Created a chunk of size 231, which is longer than the specified 1
Created a chunk of size 427, which is longer than the specified 1
Created a chunk of size 418, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 168, which is longer than the specified 1
Created a chunk of size 626, which is longer than the specified 1
Created a chunk of size 2616, which is longer than the specified 1
Created a chunk of size 1580, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 996, which is longer than the specified 1
Created a chunk of size 849, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 338, which is longer than the specified 1
Created a chunk of size 1530, which is longer than the specified 1
Created a chunk of size 215, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 2032, which is longer than the specified 1
Created a chunk of size 398, which is longer than the specified 1
Created a chunk of size 1619, which is longer than the specified 1
Created a chunk of size 700, which is longer than the specified 1
Created a chunk of size 824, which is longer than the specified 1
Created a chunk of size 356, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 510, which is longer than the specified 1
Created a chunk of size 665, which is longer than the specified 1
Created a chunk of size 1284, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 217, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 1277, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1
Created a chunk of size 380, which is longer than the specified 1
Created a chunk of size 271, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 227, which is longer than the specified 1
Created a chunk of size 224, which is longer than the specified 1
Created a chunk of size 784, which is longer than the specified 1
Created a chunk of size 971, which is longer than the specified 1
Created a chunk of size 615, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 965, which is longer than the specified 1
Created a chunk of size 234, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1
Created a chunk of size 788, which is longer than the specified 1
Created a chunk of size 650, which is longer than the specified 1
Created a chunk of size 986, which is longer than the specified 1
Created a chunk of size 799, which is longer than the specified 1
Created a chunk of size 193, which is longer than the specified 1
Created a chunk of size 1163, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 203, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1
Created a chunk of size 248, which is longer than the specified 1
Created a chunk of size 877, which is longer than the specified 1
Created a chunk of size 819, which is longer than the specified 1
Created a chunk of size 380, which is longer than the specified 1
Created a chunk of size 757, which is longer than the specified 1
Created a chunk of size 571, which is longer than the specified 1
Created a chunk of size 628, which is longer than the specified 1
Created a chunk of size 868, which is longer than the specified 1
Created a chunk of size 622, which is longer than the specified 1
Created a chunk of size 623, which is longer than the specified 1
Created a chunk of size 1084, which is longer than the specified 1

In [7]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [8]:
db_books = Chroma.from_documents(
    documents,
    embedding=HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

d:\BookRecommendation\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Admin\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [9]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='6d6bc33b-f80b-4b1a-93ca-d8452a322771', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='0ccb4bea-ea2e-47e5-9b14-9fe7d4f4d5b3', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='18e7d228-3f08-488b-a4d1-9c192098e2ad', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='501d8f15-175c-442b-bcc2-88655411fc2c', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(id='29b3fa6e-4f9f-4f9a-b230-d1453633a17c', metadata={'source': 'tagged_description.txt'}, page_content='"9780060959036 Barbara Kingsolver\'s fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel\'s intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."'),
 Document(id='d747a666-9993-4a35-af57-15dcb3e569a3', metadata={'source': 'tagged_description.txt'}, page_content='"9780786819119 Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub."'),
 Document(id='893fb574-a8b6-4c25-90ed-691b773cfbef', metadata={'source': 'tagged_description.txt'}, page_content='"9780374522599 The Control of Nature is John McPhee\'s bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters."'),
 Document(id='f9eda14d-fc66-46eb-9c51-cec9ff580516', metadata={'source': 'tagged_description.txt'}, page_content='"9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author\'s father].\' \'BL. 1986 Children\'s Editors\' Choices (BL) Children\'s Choices for 1987 (IRA/CBC) Notable 1986 Childrens\' Trade Books in Social Studies (NCSS/CBC) 1986 Children\'s Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"'),
 Document(id='ad124ed1-e73e-4c1c-817a-de1e068e8182', metadata={'source': 'tagged_description.txt'}, page_content='"9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"'),
 Document(id='58235edf-58c7-40c7-9796-7ac0a2424889', metadata={'source': 'tagged_description.txt'}, page_content='"9780802431486 Drawn from years of counseling and the author\'s own parenting experiences, this valuable resource, filled with Scripture passages and accompanying practical applications, provides principles for raising and nurturing children in these uncertain and rapidly changing times. Original."')]

In [11]:
books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))

C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  books[books["isbn13"]] = int(docs[0].page_content.split()[0].strip().strip('"'))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13012\2601303431.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [12]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [13]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,9784770028037,9784770028969,9788122200850,9788125026600,9788171565641,9788172235222,9788173031014,9788179921623,9788185300535,9789027712059
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
324,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
383,9780061144899,0061144894,When the Heart Waits,Sue Monk Kidd,Religion,http://books.google.com/books/content?id=JlP91...,From the Bestselling Author of The Secret Life...,2006.0,4.17,240.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
406,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
416,9780064406925,006440692X,Winter on the Farm,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=IvlKH...,The Little House books tell the story of a lit...,1997.0,4.13,32.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
427,9780064434874,0064434877,Christmas in the Big Woods,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=FT1Yp...,"Long ago, a little girl named Laura Ingalls li...",1997.0,4.19,32.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
436,9780064471961,0064471969,Shade's Children (rack),Garth Nix,Juvenile Fiction,http://books.google.com/books/content?id=_jlgl...,The Key to Survival Rests in the Hands of Shad...,1998.0,3.90,345.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
568,9780140139976,0140139974,Sailor Song,Ken Kesey,Fiction,http://books.google.com/books/content?id=-pPSO...,"In Alaska to film a famous children's book, th...",1993.0,3.57,533.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
991,9780192862099,019286209X,The Origins of Life,John Maynard Smith;Eörs Szathmáry,Science,http://books.google.com/books/content?id=nHDbB...,'I can recommend this book as a thoroughly int...,2000.0,4.11,192.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
1078,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQ...,Eric Carle's children's classic is the story o...,1994.0,4.29,26.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
1642,9780374522599,0374522596,The Control of Nature,John McPhee,Nature,http://books.google.com/books/content?id=p1qKQ...,The Control of Nature is John McPhee's bestsel...,1990.0,4.24,288.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
1880,9780385732550,0385732554,The Giver,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=oZRlY...,"At the age of twelve, Jonas, a young boy from ...",2006.0,4.12,208.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
1907,9780393315110,0393315118,Uncommon Ground: Rethinking the Human Place in...,William Cronon,Law,http://books.google.com/books/content?id=w04mj...,"Essays by revisionist historians, scientists, ...",1996.0,4.16,560.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
1943,9780393959055,0393959058,"Walden ; And, Resistance to Civil Government",Henry David Thoreau,Literary Collections,http://books.google.com/books/content?id=uVxnQ...,The classic chronicle of a communion with natu...,1992.0,3.95,482.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2164,9780439994798,0439994799,His Dark Materials,Philip Pullman,"Children's stories, English",http://books.google.com/books/content?id=E9ZkG...,The trilogy follows the coming of age of two c...,2001.0,4.26,1296.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2216,9780440421702,0440421705,Hoot,Carl Hiaasen,Bullying,http://books.google.com/books/content?id=uKUTo...,"Roy, who is new to his small Florida community...",2006.0,3.82,292.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2261,9780446518628,044651862X,The Celestine Prophecy,James Redfield,Fiction,http://books.google.com/books/content?id=UXolx...,You have never read a book like this before --...,1994.0,3.63,247.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2409,9780451456816,0451456815,Not of Woman Born,Constance Ash;Robert A. Silverberg,Fiction,http://books.google.com/books/content?id=nOEIA...,A collection of stories that detail modern sci...,1999.0,3.80,288.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2457,9780465016907,0465016901,The Drama of the Gifted Child,NaN,Psychology,http://books.google.com/books/content?id=TgtTz...,Why are many of the most successful people pla...,1997.0,4.09,144.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2497,9780486256429,0486256421,Galapagos,William Beebe,Nature,http://books.google.com/books/content?id=wFKrG...,More than 100 splendid illustrations enhance t...,1988.0,3.84,528.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2718,9780553382617,0553382616,The Shelters of Stone,Jean M. Auel,Fiction,http://books.google.com/books/content?id=BmAgt...,In the fifth volume of the best-selling Earth'...,2004.0,3.82,891.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2776,9780553585803,0553585800,Forty Signs of Rain,Kim Stanley Robinson,Fiction,http://books.google.com/books/content?id=TI18I...,In the first installment of a trilogy of eco-t...,2005.0,3.54,393.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2827,9780571207565,0571207561,Collected Children's Stories,Sylvia Plath,"Children's poetry, American",http://books.google.com/books/content?id=i6oCG...,"Three classic children's stories, Mrs Cherry's...",2001.0,4.22,54.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
2897,9780618111206,0618111204,Once a Wolf,Stephen R. Swinburne;Jim Brandenburg,Juvenile Nonfiction,http://books.google.com/books/content?id=UkZWu...,With powerful and rare photos by a former phot...,2001.0,4.06,48.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3000,9780671631987,0671631985,Teach Your Child to Read in 100 Easy Lessons,Siegfried Engelmann;Phyllis Haddox;Elaine Bruner,Education,http://books.google.com/books/content?id=MUucJ...,"With more than half a million copies in print,...",1986.0,4.15,395.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3214,9780689861130,0689861133,"Moo, Baa, la la La!",Sandra Boynton,Animal sounds,http://books.google.com/books/content?id=Gz40A...,Children will love joining in and imitating th...,2004.0,4.20,14.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3442,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3577,9780762413935,076241393X,The Classic Treasury of Hans Christian Andersen,Hans Christian Andersen;Christian Birmingham,Juvenile Fiction,http://books.google.com/books/content?id=cYout...,Award-winning English illustrator Christian Bi...,2002.0,4.24,156.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3581,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3765,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3834,9780802431486,0802431488,The 10 Commandments of Parenting,H. Edwin Young,Religion,http://books.google.com/books/content?id=Q1Hxj...,Drawn from years of counseling and the author'...,2005.0,4.00,224.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
3933,9780811205467,0811205460,Turtle Island,Gary Snyder,Poetry,http://books.google.com/books/content?id=xilff...,These Pulitzer Prize-winning poems and essays ...,1974.0,4.09,112.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4103,9780842331913,0842331913,Four Mothers at Chautauqua,Isabella Alden,Fiction,http://books.google.com/books/content?id=DkbhZ...,"Isabella Alden, Grace Livingston Hill's aunt a...",1997.0,4.01,265.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4185,9780878937202,087893720X,Essentials of Conservation Biology,Richard B. Primack,Science,http://books.google.com/books/content?id=spaGQ...,Essentials of Conservation Biology (Fourth Edi...,2006.0,3.89,585.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4331,9781400033850,1400033853,Providence of a Sparrow,Chris Chester,Biography & Autobiography,http://books.google.com/books/content?id=Z7RDD...,Describes the influence of a foundling baby sp...,2004.0,4.32,304.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4541,9781421509594,1421509598,The Drifting Classroom,Kazuo Umezu,Comics & Graphic Novels,http://books.google.com/books/content?id=6ME-P...,A flash flood turns the desert into a drowned ...,2007.0,3.94,192.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4607,9781561796779,1561796778,"Boomers, Xers, and Other Strangers",Rick Hicks;Kathy Hicks,Social Science,http://books.google.com/books/content?id=IogMA...,The authors maintain that children's core valu...,1999.0,3.36,384.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4713,9781576839546,1576839540,Parenting with Love and Logic,Foster Cline;Jim Fay,Family & Relationships,http://books.google.com/books/content?id=TpCtP...,Cline and Fay offer advice to help parents rai...,2006.0,4.07,271.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
4898,9781593851170,1593851170,The Nature of Play,Anthony D. Pellegrini;Peter K. Smith,Psychology,http://books.google.com/books/content?id=Nukz6...,"""Comprehensive and up to date, this tightly ed...",2005.0,4.25,308.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,...,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069,9780786808069